Display owners for relics & mythics (whenever they're implemented)
EdenServer/eden-web pull request #120
Opened 2020-08-20 03:18 UTC by rude-jerk

![image](https://user-images.githubusercontent.com/9592857/90712969-387bad80-e272-11ea-963d-f5133606d9da.png)

Displaying these on the character page is a task for a future date.

Input on styling would be great, I do prefer to avoid a single-column table, though.

2020-08-22 18:02 UTC, Mozzy4Ever commented
Single coluuuuuuuuumn

2020-08-25 23:36 UTC, bkesecker commented
A grid probably won't work well on mobile unless side scrollable.  This is a 'badge of honor' feature, so I am not sure of purpose beyond that to make it more user friendly.  Nice idea!

2020-08-27 20:12 UTC, bkesecker commented
Working in test.

![image](https://user-images.githubusercontent.com/45717129/91490198-052dc400-e8ed-11ea-8570-31f64280874e.png)

http://test.edenxi.org:8080/tools/item/amanomurakumo

2020-08-27 20:17 UTC, bkesecker requested changes

2020-08-27 20:17 UTC, bkesecker commented on api/v1/utils/items.js
> +        WHERE b.name = ? ORDER BY charname ASC;`;
`WHERE b.name = ? AND c.deleted IS NULL` should help with performance a bit.

2020-08-27 20:18 UTC, bkesecker commented
Query took 16 seconds with the 40,000 characters in the DB.

2020-08-27 20:44 UTC, rude-jerk commented
Easy enough! 

Did the query take 16 seconds without the suggested change or with it made locally? It's a bit hard to simulate that number of characters and inventories in the database, though I probably should write a script to fake it for the sake of testing locally.

2020-08-27 21:11 UTC, InoUno commented
Since it's such expensive queries (having to search through *all* items on the server), you'll probably want to cache it quite heavily.

Maybe it's better to make the server keep an updated list for each of the items, and have it refresh that list every X hours (without user action). That way users won't have to wait 10+ seconds each time they load one of the relic item pages to see results.

2020-08-27 21:27 UTC, rude-jerk commented
I can also remove one of the query joins by storing the itemids for the items to perform this with rather than the names, but didn't bother.  The DISTINCT keyword also adds a bit of overhead and can probably be pulled.

2020-09-08 22:22 UTC, rude-jerk commented
@bkesecker Can you give this a try again? I made a few changes and locally I see a fairly large query performance difference, though I admit I'm only faking ~10,000 characters in my database.

2020-10-19 14:45 UTC, slassen commented
@rude-jerk the chars table won’t be the bottleneck. It’ll be the char_inventory. I haven’t had access to the database in quite some time but you can safely assume maybe 50 inventory per character and we had maybe 40000 chars? So about 2 million items; most likely more.

2020-10-25 23:59 UTC, rude-jerk commented
Yeah, I tested this with 1.4m records in my local database and removing the items join reduced the query time by ~half.

2020-10-26 00:03 UTC, slassen commented
Cool. I will review this week.

2021-02-18 08:07 UTC, InoUno approved these changes

2021-02-18 08:14 UTC, merged